#! /bin/bash


decho () {
    echo "$@" 1>&2
}

verbose () {
    echo "$@"
    "$@"
    return $?
}

find_conda () {
    if which xmamba >& /dev/null
    then
        which mamba
    elif which conda >& /dev/null
    then
        which conda
    elif [[ -x ${HOME}/miniconda3/bin/conda ]]
    then
        echo ${HOME}/miniconda3/bin/conda
    else
        decho "Could not find conda."
        decho "Please install conda from: https://docs.conda.io/en/latest/miniconda.html"
        decho "or make sure that it can be found in your PATH"
        decho "If you install conda to the default \${HOME}/miniconda3, this script will"
        decho "detect that and you will not need to let conda modify your .bashrc (or similar init file)."
        exit 1
    fi
}

create_environment () {
    conda_exe="$1"
    path_env="$2"
    spec="$3"

    if [[ -d ${path_env} ]]
    then
        action=update
    else
        action=create
    fi

    echo "${action%?}ing environment..."

	verbose $conda_exe env ${action} -p ${path_env} -f ${spec}
    return $?
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ENVIRONMENT="${SCRIPT_DIR}/taskvine-env"

CONDA=$(find_conda)

if ! create_environment "${CONDA}" "${ENVIRONMENT}" environment.yml
then
    decho "Could not create/update environment!"
    exit 1
fi

echo "Packing environment for remote execution..."

source $(realpath taskvine-env/bin/activate)
if ! conda-pack --output taskvine-env.tar.gz
then
    decho "Could not pack environment."
    decho "This is only a problem if you wanted to submit remote workers in a batch system."
fi

cat <<EOF
    TaskVine conda environment installed succesfully.
    If conda is in your PATH, activate with:
        conda activate -p $(realpath taskvine-env)
    Otherwise, with:
        source \$(realpath taskvine-env/bin/activate)

    cd to experiments/fig-* directories to reproduce the papers results
EOF

cat <<EOF
    TaskVine conda environment installed succesfully.
    If conda is in your PATH, activate with:
        conda activate -p $(realpath taskvine-env)
    Otherwise, with:
        source \$(realpath taskvine-env/bin/activate)

    cd to experiments/fig-* directories to reproduce the papers results
EOF

exit 0

