#!/bin/sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

SUBMIT_COMMON=${SCRIPT_DIR}/vine_submit_common
if [ ! -f "$SUBMIT_COMMON" ];
then
	echo "Could not find 'vine_submit_common'" 1>&2
	exit 1
else
    ENVIRONMENT="${SCRIPT_DIR}/../taskvine-env"
    . ${ENVIRONMENT}/bin/activate ""
	. $SUBMIT_COMMON
fi

show_help()
{

	echo "  -p <parameters>          SLURM sbatch parameters."
}

slurm_parameters=""

parse_arguments()
{
	if [ -z "$cores" -o "$cores" = 0 ]
	then
		slurm_parameters="$slurm_parameters --exclusive"
	else
		slurm_parameters="$slurm_parameters --cpus-per-task $cores"
	fi

    original_count=$#

	while [ $# -gt 0 ]
	do
		case $1 in
			-p)
			shift
			slurm_parameters="$slurm_parameters $1"
			;;
			*)
			break
			;;
		esac
		shift
	done

    current_count=$#
    consumed=$((original_count - current_count))

    return $consumed
}

submit_workers_command()
{
	sbatch=`which sbatch 2>/dev/null`
	if [ $? != 0 ]
	then
		echo "$0: please add 'sbatch' to your PATH."
		exit 1
	fi

	to_submit=$count
	while [[ "$to_submit" -gt 0 ]]
	do
		to_submit=$((to_submit-1))
		sbatch --job-name vine_worker --ntasks=1 --nodes=1 $slurm_parameters <<EOF
#!/bin/sh
vine_worker $arguments $host $port
EOF
	done

}

submit_workers "$@"
